name: dlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.3.2
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - enum34=1.1.10
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.4.9
  - ffmpeg=4.2.2
  - filelock=3.9.0
  - flit-core=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.5.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.28.1
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - ipykernel=5.5.5
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.0.6
  - jupyter_core=4.12.0
  - jupyter_server=1.23.6
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert-core=7.4.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pathlib=1.0.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=19.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scikit-image=0.19.2
  - scipy=1.8.1
  - send2trash=1.8.2
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - tifffile=2019.7.26.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.2
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.19.0
    - einops==0.6.1
    - opencv-python==3.4.18.65
    - piqa==1.3.1
    - psutil==5.9.5
    - ttkthemes==3.2.2
    - ttkwidgets==0.13.0
